dist: bionic
language: node_js
node_js: '16'

services:
  - docker

branches:
  only:
    - main

jobs:
  include:
    - stage: Build
      name: 'Run Build'
      script:
        - docker build -t bryanmarc01/backend:latest .

    - stage: Test
      name: 'Run Tests'
      script:
        - docker run bryanmarc01/backend:latest npm test

    - stage: Manual Approval
      name: 'Manual Approval'
      script:
        - echo "Waiting for manual approval"
      if: type = push

    - stage: Backend Deployment
      name: 'Run Backend Deployment'
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bryanmarc01/backend:latest
      if: type = push

stages:
  - name: Build
  - name: Test
  - name: Manual Approval
    if: type = push
  - name: Deploy
    if: type = push

before_deploy:
  - echo "Starting deployment"

deploy:
  provider: script
  script: bash deploy_backend.sh
  on:
    branch: main
  skip_cleanup: true
  edge: true
  wait-for-approval: true
