dist: bionic
language: node_js
node_js: '16'

services:
  - docker

branches:
  only:
    - main

jobs:
  include:
    - stage: Build
      name: 'Build Docker Image'
      script:
        - docker build -t $DOCKER_USERNAME/backend:latest .
        - docker images  # Listar imágenes para depuración
      after_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag $DOCKER_USERNAME/backend:latest $DOCKER_USERNAME/backend:build
        - docker push $DOCKER_USERNAME/backend:build

    - stage: Test
      name: 'Run Tests'
      script:
        - docker pull $DOCKER_USERNAME/backend:build
        - docker tag $DOCKER_USERNAME/backend:build $DOCKER_USERNAME/backend:test
        - docker images  # Listar imágenes para depuración
        - docker run $DOCKER_USERNAME/backend:test

    - stage: Deploy
      name: 'Deploy Docker Image'
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull $DOCKER_USERNAME/backend:build
        - docker tag $DOCKER_USERNAME/backend:build $DOCKER_USERNAME/backend:latest
        - docker images  # Listar imágenes antes del push
        - docker push $DOCKER_USERNAME/backend:latest

stages:
  - name: Build
  - name: Test
  - name: Deploy

before_deploy:
  - echo "Starting deployment"
