dist: bionic
language: node_js
node_js: '16'

services:
  - docker

branches:
  only:
    - main

jobs:
  include:
    - stage: Build
      name: 'Build Docker Image'
      script:
        - docker build -t $DOCKER_USERNAME/backend:latest .
     

    - stage: Test
      name: 'Run Tests'
      script:
        - docker build -t $DOCKER_USERNAME/backend:test --target test .
        - docker run $DOCKER_USERNAME/backend:test

    - stage: Deploy
      name: 'Deploy Docker Image'
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/backend:latest
      if: branch = main

stages:
  - name: Build
  - name: Test
  - name: Deploy

before_deploy:
  - echo "Starting deployment"
