dist: bionic
language: node_js
node_js: '16'

services:
  - docker

branches:
  only:
    - main

jobs:
  include:
    - stage: Build
      name: 'Build Docker Image'
      script:
        - docker build -t $DOCKER_USERNAME/backend:latest .
       - docker images
  - docker tag $DOCKER_USERNAME/backend:latest $DOCKER_USERNAME/backend:latest 
    - stage: Test
      name: 'Run Tests'
      script:
        - docker build -t $DOCKER_USERNAME/backend:test --target test .
          - docker images
        - docker run $DOCKER_USERNAME/backend:test


stages:
  - name: Build
  - name: Test
  - name: Deploy

before_deploy:
  - echo "Starting deployment"
