dist: bionic
language: node_js
node_js: '16'

services:
  - docker

branches:
  only:
    - main

jobs:
  include:
    - stage: Build
      name: 'Build Docker Image'
      script:
        - docker build -t bryanmarc01/backend:latest .

    - stage: Test
      name: 'Run Tests'
      script:
        - docker run bryanmarc01/backend:latest npm test

    - stage: Deploy
      name: 'Deploy Docker Image'
      script:
        - echo "levelstoli" | docker login -u "bryanmarc01" --password-stdin
        - docker push bryanmarc01/backend:latest
      if: branch = main

stages:
  - name: Build
  - name: Test
  - name: Deploy

before_deploy:
  - echo "Starting deployment"
